In [1]:
import torch

print(torch.__version__)

2.12.0+cpu


In [2]:
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [3]:
x = torch.tensor(5)
print(x)

tensor(5)


0D Tensor (Scalar)

1D Tensor (Vector)

In [4]:
x = torch.tensor([1, 2, 3])

print(x)

tensor([1, 2, 3])


2D Tensor (Matrix)

In [5]:
x = torch.tensor([
    [1,2],
    [3,4]
])
print(x)

tensor([[1, 2],
        [3, 4]])


3D dimension

In [6]:
x = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(x)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


More dimensions = More information

shape

In [7]:
x = torch.tensor([
    [1,2],
    [3,4]
])

print(x.shape)

torch.Size([2, 2])


2 rows
2 columns

Dimension

In [8]:
print(x.ndim)

2


Data Type

In [9]:
print(x.dtype)

torch.int64


In [10]:
import torch

x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
2
torch.int64
