In [1]:
import torch
print(torch.__version__)

2.12.0+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available, using CPU")

GPU is not available, using CPU


In [23]:
a = torch.zeros(2,2)
print(a)

tensor([[0., 0.],
        [0., 0.]])


In [21]:
a = torch.tensor(a, dtype=torch.float16)
print(a)

tensor([[0.7920, 0.4153, 0.9556],
        [0.5723, 0.6035, 0.5273]], dtype=torch.float16)


C:\Users\Ayub\AppData\Local\Temp\ipykernel_15544\3984163351.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(a, dtype=torch.float16)


mathametical operations

1. scalar operations

In [7]:
x = torch.rand(2,2)
x

tensor([[0.2626, 0.0357],
        [0.0626, 0.8930]])

Addition

In [8]:
x + 3

tensor([[3.2626, 3.0357],
        [3.0626, 3.8930]])

Substraction

In [10]:
x - 2

tensor([[-1.7374, -1.9643],
        [-1.9374, -1.1070]])

Mod

In [11]:
((x*100)//3)%2

tensor([[0., 1.],
        [0., 1.]])

Power

In [12]:
x**2

tensor([[0.0689, 0.0013],
        [0.0039, 0.7975]])

Inplace operation

use for memory saving

In [13]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.3692, 0.3741, 0.9593],
        [0.1728, 0.4908, 0.6941]])
tensor([[0.8426, 0.6836, 0.5635],
        [0.7165, 0.8644, 0.7741]])


In [14]:
m + n

tensor([[1.2117, 1.0577, 1.5228],
        [0.8893, 1.3552, 1.4682]])

while this will create a whole new slot in memory we can use inplace opretor to make changes in the same memory slot of tensor

In [15]:
m.add_(n)

tensor([[1.2117, 1.0577, 1.5228],
        [0.8893, 1.3552, 1.4682]])

In [16]:
m


tensor([[1.2117, 1.0577, 1.5228],
        [0.8893, 1.3552, 1.4682]])

In [17]:
m.relu_()

tensor([[1.2117, 1.0577, 1.5228],
        [0.8893, 1.3552, 1.4682]])

copying a tensor

In [24]:
a = torch.rand(2,3)
print(a)

tensor([[0.8680, 0.6304, 0.8117],
        [0.2857, 0.5717, 0.9864]])


In [25]:
b = a.clone()

In [26]:
a

tensor([[0.8680, 0.6304, 0.8117],
        [0.2857, 0.5717, 0.9864]])

In [27]:
b

tensor([[0.8680, 0.6304, 0.8117],
        [0.2857, 0.5717, 0.9864]])

In [28]:
a[0][0] = 0

In [30]:
a


tensor([[0.0000, 0.6304, 0.8117],
        [0.2857, 0.5717, 0.9864]])

In [31]:
b

tensor([[0.8680, 0.6304, 0.8117],
        [0.2857, 0.5717, 0.9864]])

In [32]:
id(a)

2437739156720

In [33]:
id(b)

2437738737536

Tensor operations on GPU

In [34]:
torch.cuda.is_available()

False

use google colab or jupytrr notebook if nividia is not available